apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-nzoc
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0007-tenant/tkwch-fix-0075-0007-app/devfile-sample-nzoc@sha256:9f25a225c12967f3ae4aa177c42f3f1c6da1de67ab2ba100c169ce9415b67527
        name: my-nodejs
        resources: {}
status: {}
